name: flood_impact

channels:
  - conda-forge

dependencies:
 - python>=3.7
 - rasterio>=1.1
 - xarray>=0.18
 - pandas>=1.2
 - gdal
 - numpy>=1.20
 - setuptools>=50.0
 - ipython
 - nbconvert
 - notebook
 - click>=7.1
 - geopandas>=0.9
 - seaborn